---
- name: Check Disk Space
  hosts: your_target_hosts
  become: yes
  gather_facts: yes

  tasks:
    - name: Check Disk Space
      ansible.builtin.shell: df -h
      register: disk_space_output
      ignore_errors: yes

    - name: Display Disk Space
      ansible.builtin.debug:
        var: disk_space_output.stdout_lines
