---
- name: Install QEMU Guest Agent
  hosts: all
  become: yes
  tasks:
    - name: Install QEMU Guest Agent
      ansible.builtin.apt:
        name: qemu-guest-agent  # or your package manager's equivalent package name
        state: present
